# Generated by Django 4.2.7 on 2023-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_fname', models.CharField(max_length=20)),
                ('u_lname', models.CharField(max_length=20)),
                ('u_contact', models.CharField(max_length=13)),
                ('u_address', models.CharField(max_length=50)),
                ('u_email', models.EmailField(max_length=100)),
                ('u_password', models.CharField(max_length=50)),
                ('is_admin', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
