# Generated by Django 4.2.7 on 2023-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fast', '0002_rename_user_userdetails_alter_userdetails_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='otp_used',
            field=models.IntegerField(null=True),
        ),
    ]
